### ISSUE TITLE
Statusline was not rendered

### ISSUE THREAD

**Issue by 4513ECHO** [Shougo/ddu-ui-ff#31] opened 2022-05-02 04:45 UTC
## Problem Summary

The statusline was cleared as default when `'laststatus'` is 3.

## Additional Context

I think it can be fixed by the way which is same as https://github.com/Shougo/pum.vim/commit/411ac9e00de9405a0fa01acee2e1204cf2814b50

**Comment by Shougo** [comment] 2022-05-02 06:39
It works for me.  Please create the minimal vimrc.

**Comment by Shougo** [comment] 2022-05-02 06:40
My minimal vimrc.

```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-commands.vim
set rtp+=~/work/ddu-ui-ff
set rtp+=~/work/ddu-kind-file
set rtp+=~/work/ddu-filter-matcher_substring
set rtp+=~/work/ddu-source-file

set laststatus=3

call ddu#custom#patch_global({
      \   'ui': 'ff',
      \   'sourceOptions' : {
      \     '_' : {
      \       'matchers': ['matcher_substring'],
      \     }
      \   },
      \   'uiParams': {
      \     'ff': {
      \     }
      \   },
      \   'kindOptions': {
      \     'file': {
      \       'defaultAction': 'open',
      \     },
      \   },
      \ })

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction
```

If you don't upload the minimal vimrc, I will close it.

**Comment by Shougo** [comment] 2022-05-02 06:41
![スクリーンショット_2022-05-02_15-41-19](https://user-images.githubusercontent.com/41495/166194519-2522021a-842e-4ced-a4bc-273afc7a0c12.png)

Why the statusline is displayed?

**Comment by Shougo** [comment] 2022-05-02 06:55
I think the problem is bug and neovim HEAD is fixed.

**Comment by 4513ECHO** [comment] 2022-05-02 07:35
I forgot to write, we need to use floating window. And I use `NVIM v0.8.0-dev+53-g440b65c33` now.

```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-commands.vim
set rtp+=~/work/ddu-ui-ff
set rtp+=~/work/ddu-kind-file
set rtp+=~/work/ddu-filter-matcher_substring
set rtp+=~/work/ddu-source-file
" NOTE: for easy to verification
" set rtp+=~/work/lightline.vim

set laststatus=3

call ddu#custom#patch_global({
      \   'ui': 'ff',
      \   'sourceOptions' : {
      \     '_' : {
      \       'matchers': ['matcher_substring'],
      \     }
      \   },
      \   'uiParams': {
      \     'ff': {
      \       'split': 'floating',
      \     }
      \   },
      \   'kindOptions': {
      \     'file': {
      \       'defaultAction': 'open',
      \     },
      \   },
      \ })

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction
```

**Comment by Shougo** [comment] 2022-05-02 10:18
Fixed.

**Closed** 2022-05-02 10:18 UTC
